#!/usr/bin/env python3
"""Generate ``docs/STATUS.md`` from the status each document declares.

The index is generated rather than maintained. A hand-written index of what is
current is a second place for the truth to live, and the whole reason this file
exists is that the project already had several of those disagreeing with each
other. Here the document itself is the only source: each one declares its own
status in front matter, and this script collects them.

``tests/test_docs_status.py`` regenerates and compares, so the committed index
cannot drift from the documents it describes.

    python3 scripts/make_status.py           # write docs/STATUS.md
    python3 scripts/make_status.py --check   # exit 1 if it would change
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "STATUS.md"

VALID = ("current", "historical", "superseded", "partially_withdrawn", "withdrawn")

ORDER = {name: index for index, name in enumerate(VALID)}

HEADING = {
    "current": ("Vigente", "Current"),
    "historical": ("Histórico", "Historical"),
    "partially_withdrawn": ("Parcialmente retirado", "Partially withdrawn"),
    "superseded": ("Superado", "Superseded"),
    "withdrawn": ("Retirado", "Withdrawn"),
}

GLOSS = {
    "current": (
        "Se puede citar. Es lo que el proyecto sostiene hoy.",
        "Quotable. What the project holds today.",
    ),
    "historical": (
        "Correcto tal como fue escrito, en su fecha. No es una instrucción viva.",
        "Correct as written, on its date. Not a live instruction.",
    ),
    "partially_withdrawn": (
        "Una parte se sostiene y otra no. El documento dice cuál es cuál; "
        "la columna **se sostiene** lo resume.",
        "Part stands and part does not. The document says which is which; the "
        "**stands** column summarises it.",
    ),
    "superseded": (
        "Hay una medición posterior de lo mismo. Citar la sucesora.",
        "A later measurement of the same thing exists. Cite the successor.",
    ),
    "withdrawn": (
        "No citar ninguna cifra, en ninguna dirección.",
        "Do not quote a figure from it, in any direction.",
    ),
}

PREAMBLE = """# Estado de la documentación · Documentation status

> **Generado por `scripts/make_status.py`. No editar a mano.**
> Cada documento declara su propio estado en su encabezado; este índice los
> reúne. `tests/test_docs_status.py` falla si los dos dejan de coincidir.
>
> *Generated by `scripts/make_status.py`. Do not edit by hand.* Each document
> declares its own status in its front matter; this index collects them.
> `tests/test_docs_status.py` fails if the two stop agreeing.

## ES

Un resultado retirado sigue en el repositorio. Borrarlo dejaría el registro más
limpio y menos honesto: las cifras retiradas fueron publicadas, citadas y
usadas para decidir, y lo que importa es que nadie las vuelva a citar sin saber
por qué cayeron. Esta página existe para que **no haga falta abrir un documento
para saber si se puede citar**.

## EN

A withdrawn result stays in the repository. Deleting it would leave a tidier
record and a less honest one: the withdrawn figures were published, cited and
acted on, and what matters is that nobody cites them again without knowing why
they fell. This page exists so that **you do not have to open a document to
learn whether you may quote it**.
"""


def front_matter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}
    block = text[4:].split("\n---\n", 1)[0]
    fields: dict[str, str] = {}
    key = None
    for line in block.splitlines():
        if line.startswith("  ") and key:
            fields[key] = (fields[key] + " " + line.strip()).strip()
        elif ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip()
            fields[key] = "" if value == ">" else value
    return fields


def _is_translation(path: Path) -> bool:
    """True for the second half of a pair whose first half is listed already.

    A pair is one entry in this index, not two: RESULTS_V4.md and
    RESULTS_V4_ES.md are the same result in two languages, and listing both
    would restore exactly the duplication this file exists to remove. The
    canonical half is the one whose name has no language suffix; where both
    halves carry one (SPEC_EN / SPEC_ES), the English half is listed and the
    Spanish one is linked beside it.
    """
    stem = path.stem
    if not stem.endswith(("_EN", "_ES")):
        return False
    if (DOCS / f"{stem[:-3]}.md").exists():
        return True
    return stem.endswith("_ES")


def translation_of(path: Path) -> Path | None:
    """The other language of a listed document, if it exists."""
    stem = path.stem
    if stem.endswith("_EN"):
        pair = DOCS / f"{stem[:-3]}_ES.md"
        return pair if pair.exists() else None
    for suffix in ("_ES", "_EN"):
        pair = DOCS / f"{stem}{suffix}.md"
        if pair.exists():
            return pair
    return None


def collect() -> dict[str, list[tuple[str, dict[str, str]]]]:
    groups: dict[str, list[tuple[str, dict[str, str]]]] = {name: [] for name in VALID}
    for path in sorted(DOCS.glob("*.md")):
        if path.name == OUT.name or _is_translation(path):
            continue
        fields = front_matter(path)
        pair = translation_of(path)
        fields = dict(fields, _pair=pair.name if pair else "")
        status = fields.get("status")
        if status not in VALID:
            raise SystemExit(
                f"{path.name} declares status {status!r}. "
                f"One of {', '.join(VALID)} is required."
            )
        groups[status].append((path.name, fields))
    return groups


def _other(fields: dict[str, str]) -> str:
    if fields.get("lang") == "es+en":
        return "en el mismo archivo · in the same file"
    pair = fields.get("_pair", "")
    return f"[`{pair}`]({pair})" if pair else "**falta · missing**"


def render() -> str:
    groups = collect()
    out = [PREAMBLE]
    for status in sorted(VALID, key=lambda name: ORDER[name]):
        rows = groups[status]
        if not rows:
            continue
        es, en = HEADING[status]
        gloss_es, gloss_en = GLOSS[status]
        out.append(f"\n---\n\n## {es} · {en} — {len(rows)}\n")
        out.append(f"{gloss_es}\n\n*{gloss_en}*\n")
        if status == "superseded":
            out.append(
                "\n| documento | otro idioma | citar en su lugar | por qué |"
                "\n|---|---|---|---|"
            )
            for name, f in rows:
                out.append(
                    f"| `{name}` | {_other(f)} | [`{f.get('superseded_by','')}`]"
                    f"({f.get('superseded_by','')}) | {f.get('reason','')} |"
                )
        elif status == "partially_withdrawn":
            out.append(
                "\n| documento | otro idioma | se sostiene | qué cayó |"
                "\n|---|---|---|---|"
            )
            for name, f in rows:
                out.append(
                    f"| `{name}` | {_other(f)} | {f.get('stands','')} | "
                    f"{f.get('reason','')} |"
                )
        elif status in ("withdrawn", "historical"):
            out.append("\n| documento | otro idioma | por qué |\n|---|---|---|")
            for name, f in rows:
                out.append(f"| `{name}` | {_other(f)} | {f.get('reason','')} |")
        else:
            out.append("\n| documento | otro idioma | nota |\n|---|---|---|")
            for name, f in rows:
                note = f.get("note", "").strip() or "—"
                out.append(f"| [`{name}`]({name}) | {_other(f)} | {note} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    content = render()
    if arguments.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print(f"{OUT.relative_to(ROOT)} is stale. Run scripts/make_status.py.")
            return 1
        print("STATUS.md is current.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
